// shellfish ubg - game catalog
// by shrimpify
// no emojis, all lowercase

const CATEGORY_META = {
  action:         { tag: 'act', label: 'action' },
  arcade:         { tag: 'arc', label: 'arcade' },
  puzzle:         { tag: 'pzl', label: 'puzzle' },
  racing:         { tag: 'rac', label: 'racing' },
  shooter:        { tag: 'fps', label: 'shooter' },
  platformer:     { tag: 'plt', label: 'platformer' },
  strategy:       { tag: 'str', label: 'strategy' },
  sports:         { tag: 'spt', label: 'sports' },
  idle:           { tag: 'idl', label: 'idle' },
  simulation:     { tag: 'sim', label: 'simulation' },
  sandbox:        { tag: 'sbx', label: 'sandbox' },
  casual:         { tag: 'csl', label: 'casual' },
  adventure:      { tag: 'adv', label: 'adventure' },
  horror:         { tag: 'hor', label: 'horror' },
  card:           { tag: 'crd', label: 'card' },
  emulator:       { tag: 'emu', label: 'emulator' },
  rpg:            { tag: 'rpg', label: 'rpg' },
  rhythm:         { tag: 'rhy', label: 'rhythm' },
  'visual novel': { tag: 'vn',  label: 'visual novel' },
  survival:       { tag: 'srv', label: 'survival' },
  'tower defense':{ tag: 'td',  label: 'tower defense' },
  fighting:       { tag: 'fgt', label: 'fighting' },
  cooking:        { tag: 'cok', label: 'cooking' },
};

const POPULAR_GAMES = [
  'slope', 'retro bowl', 'subway surfers', 'among us', 'cookie clicker',
  'flappy bird', 'wordle', 'moto x3m', 'smash karts', 'minecraft classic',
  'run 3', '1v1.lol', 'tunnel rush', '2048', 'paper.io 2',
  'death run 3d', 'shell shockers', 'idle breakout', 'krunker',
  'eaglercraft (minecraft)', 'super mario 64', 'superhot', 'rooftop snipers',
  'temple run 2', 'vex 5', 'tanuki sunset', 'bloons tower defense',
  'papa\'s pizzeria', 'the impossible quiz', 'geometry dash (scratch)',
  'getaway shootout', 'backrooms', 'stick war', 'wolfenstein 3d',
  'basketball stars', 'omori', 'hollow knight', 'fnaf', 'cuphead',
  'pizza tower', 'celeste', 'undertale yellow', 'buckshot roulette',
  'balatro', 'ultrakill', 'hotline miami', 'papers, please',
  'the binding of isaac', 'getting over it', 'happy wheels',
  'drift hunters', 'cluster rush', 'doom', 'half life',
  'terraria', 'people playground', 'retro bowl college',
  'bloons td 5', 'melon playground', 'solar smash',
  'friday night funkin\'', 'super smash flash 2', 'jacksmith',
  'strike force heroes', 'chrono trigger', 'earthbound',
  'goldeneye 007', 'mario kart 64', 'ovo', 'level devil',
  'suika game', 'infinite craft', 'angry birds', 'jetpack joyride',
  'pokemon emerald', 'pokemon fire red', 'pac-man',
  'fancy pants adventure', 'fireboy and watergirl',
  'papa\'s freezeria', 'papa\'s sushiria',
  'super smash bros', 'zelda: link to the past',
  'donkey kong country', 'crash bandicoot', 'silent hill',
  'mortal kombat', 'street fighter 2', 'counter-strike 1.6',
];

const GAMES = [
  // === TIER 1: BIG INDIE / AAA WEB PORTS ===
  { name: "omori", url: "games/truffled/203.html", cat: "rpg", desc: "surreal psychological horror rpg, explore dreams and confront reality" },
  { name: "hollow knight", url: "games/truffled/160.html", cat: "action", desc: "metroidvania exploring the underground kingdom of hallownest" },
  { name: "celeste", url: "games/truffled/54.html", cat: "platformer", desc: "precision platformer about climbing celeste mountain (pico-8)" },
  { name: "cuphead", url: "games/truffled/68.html", cat: "action", desc: "1930s cartoon run-and-gun with hand-drawn boss fights" },
  { name: "pizza tower", url: "games/truffled/224.html", cat: "platformer", desc: "fast-paced platformer inspired by wario land with 90s pixel art" },
  { name: "balatro", url: "games/truffled/19.html", cat: "card", desc: "poker-themed roguelike deckbuilder, build illegal hands with jokers" },
  { name: "buckshot roulette", url: "games/truffled/47.html", cat: "horror", desc: "tabletop horror, russian roulette with a shotgun in a nightclub basement" },
  { name: "ultrakill", url: "games/truffled/319.html", cat: "shooter", desc: "retro fps inspired by quake and devil may cry, descend through hell" },
  { name: "undertale yellow", url: "games/truffled/320.html", cat: "rpg", desc: "fan-made undertale prequel, play as clover with a yellow soul" },
  { name: "hotline miami", url: "games/truffled/158.html", cat: "action", desc: "ultra-violent neon-drenched top-down shooter set in 1989 miami" },
  { name: "papers, please", url: "games/truffled/217.html", cat: "simulation", desc: "dystopian border inspector sim, check passports, make moral choices" },
  { name: "bendy and the ink machine", url: "games/truffled/32.html", cat: "horror", desc: "first-person horror in an abandoned animation studio where cartoons come alive" },
  { name: "the binding of isaac", url: "games/truffled/304.html", cat: "action", desc: "roguelike dungeon crawler, fight through rooms with tears as weapons" },
  { name: "the binding of isaac: rebirth", url: "games/truffled/305.html", cat: "action", desc: "rebirth remake of the binding of isaac with expanded content" },
  { name: "super meat boy", url: "games/truffled/292.html", cat: "platformer", desc: "brutal precision platformer, rescue your girlfriend from a fetus in a jar" },
  { name: "terraria", url: "games/truffled/303.html", cat: "sandbox", desc: "2d sandbox action-adventure, dig, fight, explore, build" },
  { name: "people playground", url: "games/truffled/222.html", cat: "sandbox", desc: "ragdoll physics sandbox, experiment with weapons and contraptions" },
  { name: "getting over it", url: "games/truffled/140.html", cat: "platformer", desc: "bennett foddy's infamous climbing game with a man in a cauldron" },
  { name: "iron lung", url: "games/truffled/163.html", cat: "horror", desc: "claustrophobic horror, navigate a submarine through an ocean of blood" },
  { name: "webfishing", url: "games/truffled/332.html", cat: "simulation", desc: "cozy multiplayer fishing game with pixel art vibes" },
  { name: "yume nikki", url: "games/truffled/340.html", cat: "rpg", desc: "surreal exploration rpg, wander through a hikikomori girl's dreams" },
  { name: "repo", url: "games/truffled/245.html", cat: "horror", desc: "co-op horror about repossessing items from haunted locations" },
  { name: "danganronpa", url: "games/truffled/78.html", cat: "visual novel", desc: "murder mystery visual novel, trapped students must solve class trials" },
  { name: "class of '09", url: "games/truffled/56.html", cat: "visual novel", desc: "satirical visual novel about a misanthropic teen in high school" },
  { name: "needy streamer overload", url: "games/truffled/198.html", cat: "simulation", desc: "manage a mentally unstable internet streamer, dark psychological sim" },
  { name: "oneshot", url: "games/truffled/201.html", cat: "rpg", desc: "meta rpg puzzle adventure, guide niko through a dying world" },
  { name: "karlson", url: "games/truffled/167.html", cat: "shooter", desc: "dani's milk-themed fps platformer with parkour and wallrunning" },
  { name: "karlson 2d", url: "games/truffled/168.html", cat: "platformer", desc: "2d side-scrolling version of karlson" },
  { name: "milkman karlson", url: "games/truffled/188.html", cat: "shooter", desc: "stealth-action karlson variant, deliver milk at all costs" },
  { name: "slime rancher", url: "games/truffled/269.html", cat: "simulation", desc: "farming sim raising adorable slimes on an alien planet" },
  { name: "untitled goose game", url: "games/truffled/321.html", cat: "puzzle", desc: "play as a horrible goose terrorizing a peaceful village" },
  { name: "dead plate", url: "games/truffled/81.html", cat: "horror", desc: "horror rpg about a chef with dark secrets" },
  { name: "bad time simulator", url: "games/truffled/22.html", cat: "action", desc: "sans fight simulator from undertale, practice the hardest boss" },
  { name: "deltatraveler", url: "games/truffled/83.html", cat: "rpg", desc: "deltarune/undertale fan crossover rpg, travel between timelines" },
  { name: "a dance of fire and ice", url: "games/truffled/9.html", cat: "rhythm", desc: "one-button rhythm game with precise timing" },
  { name: "osu!", url: "games/truffled/208.html", cat: "rhythm", desc: "free rhythm game with community beatmaps, click the circles" },
  { name: "peaks of yore", url: "games/truffled/221.html", cat: "adventure", desc: "first-person climbing simulator in a victorian mountaineering era" },
  { name: "gorilla tag", url: "games/truffled/147.html", cat: "action", desc: "tag game as gorillas using arm-based locomotion" },
  { name: "yandere simulator", url: "games/truffled/338.html", cat: "simulation", desc: "stealth game about a lovesick schoolgirl eliminating rivals" },
  { name: "lacey's flash games", url: "games/truffled/172.html", cat: "horror", desc: "horror game about a girl playing cursed flash games online" },
  { name: "that's not my neighbor", url: "games/gn/216.html", cat: "horror", desc: "identify doppelgangers disguised as your neighbors" },
  { name: "10 minutes till dawn", url: "games/truffled/4.html", cat: "action", desc: "vampire survivors-style roguelike shooter" },
  { name: "crazy cattle 3d", url: "games/truffled/65.html", cat: "action", desc: "viral physics-based cattle fighting game" },
  { name: "raft", url: "games/truffled/238.html", cat: "survival", desc: "ocean survival, expand your raft, gather resources, survive" },

  // === FNAF SERIES ===
  { name: "fnaf", url: "games/truffled/121.html", cat: "horror", desc: "survive nights as a security guard at freddy fazbear's pizza" },
  { name: "fnaf 2", url: "games/truffled/122.html", cat: "horror", desc: "five nights at freddy's 2, new location with more animatronics" },
  { name: "fnaf 3", url: "games/truffled/123.html", cat: "horror", desc: "springtrap haunts fazbear's fright, the horror attraction" },
  { name: "fnaf 4", url: "games/truffled/124.html", cat: "horror", desc: "nightmare animatronics terrorize a child's bedroom" },
  { name: "fnaf: sister location", url: "games/truffled/128.html", cat: "horror", desc: "work the night shift at circus baby's entertainment and rental" },
  { name: "fnaf world", url: "games/truffled/126.html", cat: "rpg", desc: "fnaf rpg spin-off, explore and battle in animatronic world" },
  { name: "fnaf: pizza simulator", url: "games/gn/191.html", cat: "horror", desc: "run your own pizzeria while surviving animatronic attacks" },
  { name: "fnaf: ultimate custom night", url: "games/truffled/129.html", cat: "horror", desc: "choose from 50+ animatronics and customize your nightmare" },
  { name: "five nights at candy's", url: "games/truffled/119.html", cat: "horror", desc: "fnaf fan-game set at candy's burgers and fries" },
  { name: "five nights at candy's 2", url: "games/truffled/120.html", cat: "horror", desc: "sequel to five nights at candy's with new mechanics" },

  // === CLASSIC FPS / RETRO PORTS ===
  { name: "doom", url: "games/truffled/88.html", cat: "shooter", desc: "id software's legendary 1993 fps, rip and tear" },
  { name: "doom 2", url: "games/truffled/89.html", cat: "shooter", desc: "hell on earth sequel with bigger levels and the super shotgun" },
  { name: "doom 3", url: "games/truffled/90.html", cat: "shooter", desc: "horror-focused doom sequel set on a mars base" },
  { name: "half life", url: "games/truffled/155.html", cat: "shooter", desc: "valve's revolutionary 1998 fps, gordon freeman's black mesa incident" },
  { name: "half life: opposing force", url: "games/truffled/156.html", cat: "shooter", desc: "half-life expansion playing as hecu marine adrian shephard" },
  { name: "quake iii arena", url: "games/truffled/237.html", cat: "shooter", desc: "id software's arena fps classic, fast deathmatch" },
  { name: "portal (flash)", url: "games/truffled/235.html", cat: "puzzle", desc: "2d flash recreation of valve's portal gun puzzle game" },
  { name: "gta vice city", url: "games/truffled/150.html", cat: "action", desc: "rockstar's 1980s miami open-world crime game" },
  { name: "resident evil", url: "https://truffled.lol/iframe.html?url=/gamefile/re1.html", cat: "horror", desc: "capcom's original 1996 survival horror classic" },
  { name: "resident evil 2", url: "https://truffled.lol/iframe.html?url=/gamefile/re2.html", cat: "horror", desc: "raccoon city police station zombie survival" },
  { name: "fallout", url: "games/truffled/107.html", cat: "rpg", desc: "interplay's 1997 post-apocalyptic crpg" },
  { name: "fallout 2", url: "games/truffled/108.html", cat: "rpg", desc: "sequel expanding the wasteland" },
  { name: "final fantasy vii", url: "games/truffled/113.html", cat: "rpg", desc: "square's legendary 1997 jrpg via psx emulation" },
  { name: "lego star wars", url: "games/truffled/177.html", cat: "adventure", desc: "the classic lego star wars action-adventure" },
  { name: "baldur's gate 2", url: "games/truffled/31.html", cat: "rpg", desc: "bioware's legendary crpg sequel" },
  { name: "zelda: ocarina of time", url: "games/truffled/308.html", cat: "adventure", desc: "nintendo's 1998 masterpiece via n64 emulation" },

  // === MORE INDIE HORROR / MISC ===
  { name: "slender: the 8 pages", url: "games/truffled/267.html", cat: "horror", desc: "collect 8 pages while avoiding slender man" },
  { name: "amanda the adventurer", url: "games/truffled/11.html", cat: "horror", desc: "found-footage horror about a creepy children's tv show" },
  { name: "fears to fathom: home alone", url: "games/truffled/133.html", cat: "horror", desc: "short horror based on true scary stories" },
  { name: "kindergarten", url: "games/truffled/169.html", cat: "adventure", desc: "dark humor adventure in a twisted kindergarten" },
  { name: "kindergarten 2", url: "games/truffled/170.html", cat: "adventure", desc: "sequel set in a new school with returning characters" },
  { name: "bad parenting", url: "games/truffled/20.html", cat: "horror", desc: "short horror experience about neglected children" },
  { name: "baldi's basics plus", url: "games/truffled/24.html", cat: "horror", desc: "expanded baldi's basics with procedural schools" },
  { name: "baldi's basics classic", url: "games/truffled/25.html", cat: "horror", desc: "remastered version of the original edu-horror parody" },
  { name: "endoparasitic", url: "games/gn/286.html", cat: "horror", desc: "drag yourself through a space station with one arm, fighting parasites" },

  // === RETRO CONSOLE PORTS ===
  { name: "sonic 1", url: "games/truffled/279.html", cat: "platformer", desc: "sega's original genesis classic, gotta go fast" },
  { name: "sonic 2", url: "games/truffled/280.html", cat: "platformer", desc: "sonic the hedgehog 2, twice as fast with tails" },
  { name: "sonic 3", url: "games/truffled/281.html", cat: "platformer", desc: "sonic 3 & knuckles, the ultimate genesis platformer" },
  { name: "sonic cd", url: "games/truffled/282.html", cat: "platformer", desc: "sonic cd with time travel mechanics" },
  { name: "parappa the rapper", url: "games/truffled/219.html", cat: "rhythm", desc: "psx rhythm game pioneer, you gotta believe" },
  { name: "taiko no tatsujin", url: "games/truffled/297.html", cat: "rhythm", desc: "bandai namco's iconic drum rhythm game" },
  { name: "pokemon blue", url: "games/truffled/229.html", cat: "rpg", desc: "game boy pokemon via emulation, catch em all" },
  { name: "mario party", url: "games/truffled/183.html", cat: "casual", desc: "n64 mario party via emulation, party with friends" },

  // === TOWER DEFENSE ===
  { name: "bloons td 5", url: "games/truffled/44.html", cat: "tower defense", desc: "monkey tower defense classic with tons of towers" },
  { name: "bloons td 6", url: "games/truffled/45.html", cat: "tower defense", desc: "latest mainline bloons tower defense" },
  { name: "plants vs zombies", url: "games/truffled/226.html", cat: "tower defense", desc: "popcap's iconic plants vs zombies defense" },
  { name: "plants vs zombies 2", url: "games/truffled/227.html", cat: "tower defense", desc: "sequel with time travel and new plant types" },

  // === POPULAR BROWSER GAMES W/ BETTER SOURCES ===
  { name: "happy wheels", url: "games/truffled/157.html", cat: "action", desc: "gory ragdoll physics obstacle game with level editor" },
  { name: "drift hunters", url: "games/truffled/96.html", cat: "racing", desc: "3d drifting game with car customization" },
  { name: "cluster rush", url: "games/truffled/58.html", cat: "platformer", desc: "first-person platformer jumping between moving trucks" },
  { name: "melon playground", url: "games/truffled/187.html", cat: "sandbox", desc: "physics sandbox with destructible humanoid melons" },
  { name: "solar smash", url: "games/truffled/277.html", cat: "simulation", desc: "destroy planets with weapons of cosmic destruction" },
  { name: "polytrack", url: "games/truffled/234.html", cat: "racing", desc: "low-poly racing track creator and racer" },
  { name: "retro bowl college", url: "games/truffled/247.html", cat: "sports", desc: "college football variant of retro bowl" },
  { name: "bitlife", url: "games/truffled/35.html", cat: "simulation", desc: "text-based life simulator, live your best life" },
  { name: "ages of conflict", url: "games/gn/444.html", cat: "strategy", desc: "worldbox-like civilization sim with warring nations" },
  { name: "world box", url: "games/gn/174.html", cat: "simulation", desc: "god simulator sandbox, create civilizations and destroy them" },
  { name: "peggle", url: "games/truffled/220.html", cat: "puzzle", desc: "popcap's addictive ball-dropping puzzle game" },

  // === ORIGINAL 3KH0 COLLECTION ===
  { name: "slope", url: "games/3kh0/slope/index.html", cat: "action", desc: "fast-paced 3d ball-rolling game, dodge obstacles on a steep slope" },
  { name: "retro bowl", url: "games/3kh0/retro-bowl/index.html", cat: "sports", desc: "retro-style american football management and gameplay" },
  { name: "subway surfers", url: "games/truffled/289.html", cat: "action", desc: "endless runner surfing through subway tracks dodging trains" },
  { name: "among us", url: "games/3kh0/among-us/index.html", cat: "strategy", desc: "social deduction game, find the impostor among crewmates" },
  { name: "cookie clicker", url: "games/3kh0/cookie-clicker/index.html", cat: "idle", desc: "click cookies to build a cookie empire, classic idle game" },
  { name: "flappy bird", url: "games/3kh0/flappy-bird/index.html", cat: "arcade", desc: "tap to fly through pipe gaps in this notoriously hard game" },
  { name: "wordle", url: "games/3kh0/wordle/index.html", cat: "puzzle", desc: "guess the five-letter word in six tries with color feedback" },
  { name: "idle breakout", url: "games/3kh0/idle-breakout/index.html", cat: "idle", desc: "idle incremental version of the classic brick-breaking game" },
  { name: "death run 3d", url: "games/3kh0/death-run-3d/index.html", cat: "action", desc: "high-speed first-person tunnel runner with neon visuals" },
  { name: "moto x3m", url: "games/3kh0/motox3m/index.html", cat: "racing", desc: "extreme motorcycle stunt racing through obstacle-filled levels" },
  { name: "moto x3m pool party", url: "games/3kh0/motox3m-pool/index.html", cat: "racing", desc: "summer-themed moto x3m with pool and water park obstacles" },
  { name: "moto x3m spooky land", url: "games/3kh0/motox3m-spooky/index.html", cat: "racing", desc: "halloween-themed moto x3m with spooky obstacles" },
  { name: "moto x3m winter", url: "games/3kh0/motox3m-winter/index.html", cat: "racing", desc: "winter-themed moto x3m with icy tracks and snow" },
  { name: "vex 3", url: "games/3kh0/vex3/index.html", cat: "platformer", desc: "challenging stick-figure platformer with deadly traps" },
  { name: "vex 4", url: "games/3kh0/vex4/index.html", cat: "platformer", desc: "fourth installment of the vex platformer series" },
  { name: "vex 5", url: "games/3kh0/vex5/index.html", cat: "platformer", desc: "fifth vex with harder levels and new mechanics" },
  { name: "vex 6", url: "games/3kh0/vex6/index.html", cat: "platformer", desc: "sixth entry with advanced parkour challenges" },
  { name: "smash karts", url: "games/3kh0/smashkarts/index.html", cat: "racing", desc: "multiplayer kart battle arena with power-ups and weapons" },
  { name: "paper.io 2", url: "games/3kh0/paperio2/index.html", cat: "arcade", desc: "claim territory by drawing shapes, avoid other players" },
  { name: "eaglercraft (minecraft)", url: "games/3kh0/minecraft/index.html", cat: "sandbox", desc: "browser-based minecraft port with survival and creative modes" },
  { name: "minecraft classic", url: "games/3kh0/minecraft-classic/index.html", cat: "sandbox", desc: "official minecraft classic creative mode in the browser" },
  { name: "precision client (eaglercraft)", url: "games/3kh0/precision-client/index.html", cat: "sandbox", desc: "enhanced eaglercraft client with pvp optimizations" },
  { name: "temple run 2", url: "games/3kh0/temple-run-2/index.html", cat: "action", desc: "run through ancient temple ruins, dodge obstacles, collect coins" },
  { name: "tanuki sunset", url: "games/3kh0/tanuki-sunset/index.html", cat: "racing", desc: "chill longboarding as a raccoon on a sunset highway" },
  { name: "bloons tower defense", url: "games/3kh0/bloonstd/index.html", cat: "tower defense", desc: "place monkey towers to pop waves of bloons" },
  { name: "bloons tower defense 2", url: "games/3kh0/bloonstd2/index.html", cat: "tower defense", desc: "sequel with more towers and bloon types" },
  { name: "duck life", url: "games/3kh0/ducklife1/index.html", cat: "simulation", desc: "train your duck in various skills to win races" },
  { name: "duck life 2", url: "games/3kh0/ducklife2/index.html", cat: "simulation", desc: "sequel with more training mini-games and races" },
  { name: "duck life 3", url: "games/3kh0/ducklife3/index.html", cat: "simulation", desc: "third duck life with evolution mechanics" },
  { name: "duck life 4", url: "games/truffled/100.html", cat: "simulation", desc: "fourth installment with multiple duck breeds" },
  { name: "learn to fly", url: "games/3kh0/learntofly/index.html", cat: "arcade", desc: "launch a penguin off a ramp and upgrade to fly further" },
  { name: "basketball stars", url: "games/3kh0/basketball-stars/index.html", cat: "sports", desc: "1v1 basketball with shooting and dribbling mechanics" },
  { name: "cut the rope", url: "games/3kh0/ctr/index.html", cat: "puzzle", desc: "physics puzzle, cut ropes to feed candy to om nom" },
  { name: "cut the rope: holiday gift", url: "games/3kh0/ctr-holiday/index.html", cat: "puzzle", desc: "holiday-themed cut the rope with festive levels" },
  { name: "cut the rope: time travel", url: "games/3kh0/ctr-tr/index.html", cat: "puzzle", desc: "time travel themed with dual om nom feeding" },
  { name: "rooftop snipers", url: "games/3kh0/rooftop-snipers/index.html", cat: "action", desc: "two-player rooftop shooting duel with ragdoll physics" },
  { name: "getaway shootout", url: "games/3kh0/getaway-shootout/index.html", cat: "action", desc: "chaotic two-player race to the getaway vehicle" },
  { name: "stick war", url: "games/3kh0/stickwar/index.html", cat: "strategy", desc: "command stick figure armies in real-time strategy battles" },
  { name: "wolfenstein 3d", url: "games/3kh0/wolf3d/index.html", cat: "shooter", desc: "classic 1992 first-person shooter, escape castle wolfenstein" },
  { name: "tank trouble 2", url: "games/3kh0/tank-trouble-2/index.html", cat: "action", desc: "multiplayer tank battle in a maze with ricocheting bullets" },
  { name: "hexgl", url: "games/3kh0/HexGL/index.html", cat: "racing", desc: "futuristic webgl racing game inspired by f-zero" },
  { name: "superhot", url: "games/3kh0/superhot/index.html", cat: "shooter", desc: "time moves only when you move, innovative fps puzzle shooter" },
  { name: "super mario 64", url: "games/3kh0/sm64/index.html", cat: "platformer", desc: "browser port of the classic n64 3d platformer" },
  { name: "flash tetris", url: "games/3kh0/flashtetris/index.html", cat: "puzzle", desc: "classic tetris block-stacking puzzle game" },
  { name: "geometry dash (scratch)", url: "games/3kh0/geodash/index.html", cat: "platformer", desc: "rhythm-based platformer through geometric obstacles" },
  { name: "cubefield", url: "games/3kh0/cubefield/index.html", cat: "arcade", desc: "navigate through an endless field of cubes at increasing speed" },
  { name: "draw the hill", url: "games/3kh0/draw-the-hill/index.html", cat: "casual", desc: "draw hills and slopes for a ball to roll across" },
  { name: "elastic man", url: "games/3kh0/elasticman/index.html", cat: "casual", desc: "stretch and distort a 3d face with satisfying elastic physics" },
  { name: "hextris", url: "games/3kh0/hextris/index.html", cat: "puzzle", desc: "hexagonal twist on tetris, rotate to match falling colors" },
  { name: "solitaire", url: "games/3kh0/solitaire/index.html", cat: "card", desc: "classic klondike solitaire card game" },
  { name: "minesweeper", url: "games/3kh0/minesweeper/index.html", cat: "puzzle", desc: "classic mine-finding logic puzzle game" },
  { name: "krunker", url: "games/3kh0/krunker/index.html", cat: "shooter", desc: "fast-paced multiplayer fps with pixelated graphics" },
  { name: "grindcraft", url: "games/3kh0/grindcraft/index.html", cat: "idle", desc: "minecraft-themed idle crafting and resource management" },
  { name: "sort the court", url: "games/3kh0/sort-the-court/index.html", cat: "simulation", desc: "rule a kingdom by making yes-or-no decisions" },
  { name: "there is no game", url: "games/3kh0/there-is-no-game/index.html", cat: "puzzle", desc: "meta point-and-click that insists you're not playing a game" },
  { name: "world's hardest game", url: "games/3kh0/worlds-hardest-game/index.html", cat: "arcade", desc: "navigate a red square through brutally difficult obstacle courses" },
  { name: "world's hardest game 2", url: "games/3kh0/worlds-hardest-game-2/index.html", cat: "arcade", desc: "even harder sequel with more impossible levels" },
  { name: "soldier legend", url: "games/3kh0/soldier-legend/index.html", cat: "shooter", desc: "side-scrolling run-and-gun shooter with weapon upgrades" },
  { name: "breaking the bank", url: "games/3kh0/breakingthebank/index.html", cat: "adventure", desc: "henry stickmin choose-your-own-adventure bank heist" },
  { name: "stealing the diamond", url: "games/3kh0/stealingthediamond/index.html", cat: "adventure", desc: "henry stickmin steals the tunisian diamond from a museum" },
  { name: "backrooms", url: "games/3kh0/backrooms/index.html", cat: "horror", desc: "explore the eerie, liminal backrooms in first person" },
  { name: "the impossible quiz", url: "games/3kh0/impossiblequiz/index.html", cat: "puzzle", desc: "absurd trivia with trick questions and unexpected answers" },
  { name: "craftmine", url: "games/3kh0/craftmine/index.html", cat: "sandbox", desc: "2d minecraft-inspired sandbox building and survival" },
  { name: "rolly vortex", url: "games/3kh0/rolly-vortex/index.html", cat: "arcade", desc: "roll through a vortex tunnel dodging colorful obstacles" },
  { name: "big tower tiny square", url: "games/3kh0/btts/index.html", cat: "platformer", desc: "precision platformer, tiny square ascends a massive tower" },
  { name: "helicopter", url: "games/3kh0/helicopter/index.html", cat: "arcade", desc: "classic one-button helicopter cave flyer" },
  { name: "double wires", url: "games/3kh0/doublewires/index.html", cat: "arcade", desc: "swing through the city with two grappling wires" },
  { name: "interactive buddy", url: "games/3kh0/interactivebuddy/index.html", cat: "casual", desc: "interact with a ragdoll buddy using various tools" },
  { name: "stack", url: "games/3kh0/stack/index.html", cat: "arcade", desc: "stack blocks as high as possible by timing your taps" },
  { name: "papa's pizzeria", url: "games/3kh0/papaspizzaria/index.html", cat: "simulation", desc: "manage a pizza shop, take orders, make and serve pizzas" },
  { name: "box head: 2play", url: "games/3kh0/boxhead2play/index.html", cat: "shooter", desc: "top-down zombie shooter with co-op and weapon upgrades" },
  { name: "creative kill chamber", url: "games/3kh0/creativekillchamber/index.html", cat: "adventure", desc: "point-and-click puzzle using creative escape methods" },
  { name: "tube jumpers", url: "games/3kh0/tube-jumpers/index.html", cat: "arcade", desc: "multiplayer party game on tubes with waves and sharks" },
  { name: "achievement unlocked", url: "games/3kh0/achievementunlocked/index.html", cat: "platformer", desc: "meta-game where the goal is to unlock all achievements" },
  { name: "hex empire", url: "games/3kh0/hexempire/index.html", cat: "strategy", desc: "turn-based hex grid strategy, conquer territories" },
  { name: "bloxors", url: "games/3kh0/bloxors/index.html", cat: "puzzle", desc: "roll a rectangular block to drop it through the goal hole" },
  { name: "the final earth", url: "games/3kh0/the-final-earth/index.html", cat: "simulation", desc: "vertical city-builder managing resources and growing a colony" },
  { name: "push the square", url: "games/3kh0/push-the-square/index.html", cat: "arcade", desc: "push other squares off the platform while staying on" },
  { name: "just one boss", url: "games/3kh0/just-one-boss/index.html", cat: "action", desc: "bullet-hell fight against a single increasingly difficult boss" },
  { name: "sand game", url: "games/3kh0/sand-game/index.html", cat: "casual", desc: "sandbox physics with falling sand, water, fire elements" },
  { name: "snowbattle", url: "games/3kh0/snowbattle/index.html", cat: "action", desc: "snowball fight battle game with multiplayer" },
  { name: "cannon basketball 4", url: "games/3kh0/cannon-basketball-4/index.html", cat: "puzzle", desc: "aim and shoot a basketball from a cannon into the hoop" },
  { name: "cell machine", url: "games/3kh0/cell-machine/index.html", cat: "puzzle", desc: "cellular automata puzzle, program cells to solve challenges" },
  { name: "deal or no deal", url: "games/3kh0/deal-or-no-deal/index.html", cat: "casual", desc: "browser version of the tv game show" },
  { name: "defend the tank", url: "games/3kh0/defend-the-tank/index.html", cat: "strategy", desc: "tower defense protecting your tank from enemy waves" },
  { name: "doge miner", url: "games/3kh0/DogeMiner/index.html", cat: "idle", desc: "idle clicker mining dogecoins to reach the moon" },
  { name: "evil glitch", url: "games/3kh0/evil-glitch/index.html", cat: "platformer", desc: "glitch-themed platformer with retro aesthetics" },
  { name: "factory balls forever", url: "games/3kh0/factoryballs/index.html", cat: "puzzle", desc: "logic puzzle, paint and decorate balls to match a target" },
  { name: "idle shark", url: "games/3kh0/idle-shark/index.html", cat: "idle", desc: "idle clicker where you evolve and grow a shark" },
  { name: "cs:go clicker", url: "games/3kh0/csgo-clicker/index.html", cat: "idle", desc: "cs:go themed idle clicker, open cases and collect skins" },
  { name: "particle clicker", url: "games/3kh0/particle-clicker/index.html", cat: "idle", desc: "cern-inspired idle clicker about particle physics research" },
  { name: "polybranch", url: "games/3kh0/polybranch/index.html", cat: "arcade", desc: "navigate a growing branch through polygon obstacles" },
  { name: "stack bump 3d", url: "games/3kh0/stack-bump-3d/index.html", cat: "arcade", desc: "stack rings and bump through obstacles in 3d" },
  { name: "adrenaline challenge", url: "games/3kh0/adrenalinechallenge/index.html", cat: "racing", desc: "fast-paced racing with adrenaline-pumping tracks" },
  { name: "avalanche", url: "games/3kh0/avalanche/index.html", cat: "arcade", desc: "dodge falling blocks in this fast-paced survival game" },
  { name: "big red button", url: "games/3kh0/bigredbutton/index.html", cat: "casual", desc: "simple but addictive game centered around a big red button" },
  { name: "black knight", url: "games/3kh0/blackknight/index.html", cat: "action", desc: "medieval action game playing as a black knight" },
  { name: "champion archer", url: "games/3kh0/championarcher/index.html", cat: "sports", desc: "precision archery, aim and shoot at targets for points" },
  { name: "connect 3", url: "games/3kh0/connect3/index.html", cat: "puzzle", desc: "match-three puzzle game with colorful pieces" },
  { name: "circlo", url: "games/3kh0/circlo/index.html", cat: "puzzle", desc: "guide a growing circle through maze-like levels" },
  { name: "edge not found", url: "games/3kh0/edgenotfound/index.html", cat: "platformer", desc: "platformer with invisible edges" },
  { name: "endless war 3", url: "games/3kh0/endlesswar3/index.html", cat: "shooter", desc: "top-down military shooter with vehicles and campaigns" },
  { name: "flappy 2048", url: "games/3kh0/flappy-2048/index.html", cat: "arcade", desc: "mashup of flappy bird and 2048" },
  { name: "hacker typer", url: "games/3kh0/hackertype/index.html", cat: "casual", desc: "press any key to look like a movie hacker" },
  { name: "hover bot arena", url: "games/3kh0/hba/index.html", cat: "action", desc: "arena combat with hovering robots and weapons" },
  { name: "kitten cannon", url: "games/3kh0/kittencannon/index.html", cat: "arcade", desc: "launch a kitten from a cannon for max distance" },
  { name: "matrix rampage", url: "games/3kh0/matrixrampage/index.html", cat: "action", desc: "matrix-themed action with bullet-time combat" },
  { name: "mini putt", url: "games/3kh0/miniputt/index.html", cat: "sports", desc: "miniature golf with creative holes and obstacles" },
  { name: "missiles", url: "games/3kh0/missiles/index.html", cat: "arcade", desc: "dodge incoming missiles as long as possible" },
  { name: "ns-shaft", url: "games/3kh0/ns-shaft/index.html", cat: "arcade", desc: "fall down platforms while avoiding spikes at the top" },
  { name: "pandemic 2", url: "games/3kh0/pandemic2/index.html", cat: "strategy", desc: "evolve a disease to infect the entire world" },
  { name: "papery planes", url: "games/3kh0/papery-planes/index.html", cat: "casual", desc: "throw paper airplanes through obstacles" },
  { name: "smoking barrels", url: "games/3kh0/smokingbarrels/index.html", cat: "shooter", desc: "western quick-draw duels" },
  { name: "swerve", url: "games/3kh0/swerve/index.html", cat: "arcade", desc: "swerve through traffic and obstacles at high speed" },
  { name: "tactical assassin 2", url: "games/3kh0/tacticalassasin2/index.html", cat: "shooter", desc: "sniper mission game with precision shots" },
  { name: "the battle", url: "games/3kh0/thebattle/index.html", cat: "strategy", desc: "strategic battle simulation game" },
  { name: "the heist", url: "games/3kh0/theheist/index.html", cat: "adventure", desc: "heist-themed choose-your-path adventure" },
  { name: "this is the only level", url: "games/3kh0/thisistheonlylevel/index.html", cat: "puzzle", desc: "replay the same level with different rules each time" },
  { name: "toss the turtle", url: "games/3kh0/tosstheturtle/index.html", cat: "arcade", desc: "launch a turtle from a cannon for distance" },
  { name: "canyon defense", url: "games/3kh0/canyondefense/index.html", cat: "tower defense", desc: "tower defense set in a canyon" },
  { name: "battle for gondor", url: "games/3kh0/battleforgondor/index.html", cat: "tower defense", desc: "lotr themed tower defense, defend gondor" },
  { name: "web retro (emulator)", url: "games/3kh0/webretro-local/index.html", cat: "emulator", desc: "browser-based retro console emulator" },
  { name: "1v1.space", url: "games/3kh0/1v1space/index.html", cat: "shooter", desc: "two-player space combat in zero gravity" },
  { name: "9007199254740992", url: "games/3kh0/9007199254740992/index.html", cat: "puzzle", desc: "extreme 2048, merge tiles to impossibly high numbers" },
  { name: "you are jeff bezos", url: "games/3kh0/you-are-bezos/index.html", cat: "casual", desc: "try to spend all of jeff bezos' fortune" },
  { name: "mario", url: "games/3kh0/mario/index.html", cat: "platformer", desc: "classic super mario bros in the browser" },
  { name: "n-gon", url: "games/3kh0/n-gon/index.html", cat: "shooter", desc: "physics-based roguelike shooter" },
  { name: "exo", url: "games/3kh0/exo/index.html", cat: "arcade", desc: "minimalist space survival" },
  { name: "storm the house 2", url: "games/3kh0/stormthehouse2/index.html", cat: "action", desc: "defend your house from stick figure invaders" },
  { name: "game inside a game", url: "games/3kh0/game-inside/index.html", cat: "puzzle", desc: "recursive meta game with nested games" },

  // === EXTERNAL HOSTS ===
  { name: "2048", url: "games/2048/index.html", cat: "puzzle", desc: "original 2048 sliding number puzzle" },
  { name: "doge 2048", url: "https://doge2048.com/", cat: "puzzle", desc: "doge meme themed 2048 with shiba inu images" },
  { name: "2048 cupcakes", url: "https://doge2048.com/2048-cupcakes", cat: "puzzle", desc: "cupcake-themed 2048" },
  { name: "doodle cricket", url: "games/doodle/2048-cricket.html", cat: "sports", desc: "google doodle cricket game" },
  { name: "doodle baseball", url: "games/doodle/doodle-baseball.html", cat: "sports", desc: "google doodle baseball" },
  { name: "doodle jump", url: "games/doodle/doodle-jump/index.html", cat: "arcade", desc: "bounce a doodler higher on platforms" },
  { name: "google snake", url: "games/doodle/doodle-snake.html", cat: "arcade", desc: "google's snake game, eat apples and grow" },
  { name: "dinosaur game", url: "https://dinosaurgame.app/", cat: "arcade", desc: "chrome's t-rex runner, jump cacti and duck birds" },

  // === SZ GAMES ===
  { name: "tunnel rush", url: "games/sz/games/tunnel-rush/index.html", cat: "action", desc: "high-speed 3d tunnel runner dodging barriers" },
  { name: "1v1.lol", url: "games/sz/lol/index.html", cat: "shooter", desc: "build-and-shoot battle game similar to fortnite" },
  { name: "run 3", url: "games/sz/run3/index.html", cat: "platformer", desc: "endless runner in space tunnels, defy gravity" },
  { name: "escaping the prison", url: "games/sz/games/escaping - the prision.html", cat: "adventure", desc: "henry stickmin choose-your-path prison escape" },
  { name: "fleeing the complex", url: "games/sz/games/fleeing-the-complex.html", cat: "adventure", desc: "henry stickmin escape from high-security complex" },
  { name: "slide in the woods", url: "games/sz/games/woods.html", cat: "horror", desc: "creepy slide playground horror in dark woods" },

  // === MULTIPLAYER / EXTERNAL ===
  { name: "shell shockers", url: "https://shellshock.io/", cat: "shooter", desc: "multiplayer fps where you play as eggs with guns" },
  { name: "smash karts (official)", url: "https://smashkarts.io/", cat: "racing", desc: "official multiplayer 3d kart battle arena" },
  { name: "spend elon musk money", url: "https://spendelonmoney.org/", cat: "casual", desc: "try to spend all of elon musk's billions" },

  // =============================================
  // === NEW: UGS SINGLE-FILE GAMES COLLECTION ===
  // =============================================

  // --- RETRO CONSOLE CLASSICS (N64 / SNES / GBA / PS1 / NES) ---
  { name: "chrono trigger", url: "games/ugs/clchronotrigger.html", cat: "rpg", desc: "square's legendary snes time-traveling jrpg, one of the greatest ever made" },
  { name: "earthbound", url: "games/ugs/clearthbound.html", cat: "rpg", desc: "quirky snes rpg about a boy saving the world from an alien threat" },
  { name: "goldeneye 007", url: "games/ugs/clgoldeneye007.html", cat: "shooter", desc: "rare's legendary n64 fps, james bond stealth and action" },
  { name: "banjo-kazooie", url: "games/ugs/clbanjokazooie.html", cat: "platformer", desc: "rare's n64 collectathon platformer with a bear and bird duo" },
  { name: "banjo-tooie", url: "games/ugs/clbanjotooie.html", cat: "platformer", desc: "sequel with bigger worlds and interconnected levels" },
  { name: "conker's bad fur day", url: "games/ugs/clconkersbadfurday.html", cat: "platformer", desc: "rare's mature-rated n64 platformer with crude humor" },
  { name: "donkey kong country", url: "games/ugs/cldonkeykongcountry.html", cat: "platformer", desc: "rare's snes masterpiece with pre-rendered 3d graphics" },
  { name: "donkey kong country 2", url: "games/ugs/cldonkeykongcountry2.html", cat: "platformer", desc: "diddy's kong quest, one of the best snes platformers" },
  { name: "donkey kong 64", url: "games/ugs/cldonkeykong64.html", cat: "platformer", desc: "rare's massive n64 3d collectathon platformer" },
  { name: "star fox 64", url: "games/ugs/clstarfox64.html", cat: "shooter", desc: "do a barrel roll! n64 rail shooter classic" },
  { name: "mega man x", url: "games/ugs/clmegamanx.html", cat: "platformer", desc: "capcom's snes action-platformer, upgraded mega man" },
  { name: "mega man", url: "games/ugs/clmegaman.html", cat: "platformer", desc: "capcom's original nes robot master gauntlet" },
  { name: "mega man 2", url: "games/ugs/clmegaman2.html", cat: "platformer", desc: "widely considered the best classic mega man" },
  { name: "mega man 3", url: "games/ugs/clmegaman3.html", cat: "platformer", desc: "nes classic with slide move and rush the dog" },
  { name: "mega man legends", url: "games/ugs/clmegamanlegends.html", cat: "adventure", desc: "3d mega man adventure on the ps1" },
  { name: "metal gear solid", url: "games/ugs/clmetalgearsolid.html", cat: "action", desc: "hideo kojima's stealth masterpiece via gba adaptation" },
  { name: "golden sun", url: "games/ugs/clgoldensun.html", cat: "rpg", desc: "camelot's acclaimed gba jrpg with djinn system" },
  { name: "fire emblem", url: "games/ugs/clfireemblem.html", cat: "strategy", desc: "the gba game that brought fire emblem to the west" },
  { name: "zelda: majora's mask", url: "games/ugs/clmajorasmask.html", cat: "adventure", desc: "n64 zelda with a 3-day time loop and dark themes" },
  { name: "zelda: link to the past", url: "games/ugs/cllinktothepast.html", cat: "adventure", desc: "the snes zelda that defined the series' formula" },
  { name: "zelda: minish cap", url: "games/ugs/cllozminishcap.html", cat: "adventure", desc: "gba zelda where link shrinks to tiny size" },
  { name: "mario kart 64", url: "games/ugs/clmariokart64.html", cat: "racing", desc: "the n64 kart racer that defined multiplayer gaming" },
  { name: "mario kart ds", url: "games/ugs/clmariokartds.html", cat: "racing", desc: "portable mario kart with mission mode and snaking" },
  { name: "super mario world", url: "games/ugs/clsupermarioworld.html", cat: "platformer", desc: "snes launch title, mario's greatest 2d adventure with yoshi" },
  { name: "new super mario bros", url: "games/ugs/clnewsupermariobros.html", cat: "platformer", desc: "ds mario with modern 2.5d graphics and classic gameplay" },
  { name: "super mario rpg", url: "games/ugs/clsupermariorpg.html", cat: "rpg", desc: "square x nintendo snes rpg, mario's first rpg adventure" },
  { name: "mario & luigi: superstar saga", url: "games/ugs/clmarioandluigisuperstarsaga.html", cat: "rpg", desc: "gba rpg with brothers working together in beanbean kingdom" },
  { name: "super smash bros", url: "games/ugs/clsupersmashbros.html", cat: "fighting", desc: "the original n64 fighting game with nintendo all-stars" },
  { name: "paper mario", url: "games/ugs/clpapermario.html", cat: "rpg", desc: "n64 rpg with paper-thin characters and charming world" },
  { name: "castlevania: aria of sorrow", url: "games/ugs/clcastlevaniaariaofsorrow.html", cat: "action", desc: "gba metroidvania collecting monster souls in dracula's castle" },
  { name: "castlevania (nes)", url: "games/ugs/clcastlevanianes.html", cat: "platformer", desc: "konami's original 1986 vampire-slaying classic" },
  { name: "castlevania ii", url: "games/ugs/clcastlevania2.html", cat: "platformer", desc: "simon's quest, open-world nes castlevania sequel" },
  { name: "castlevania iii", url: "games/ugs/clcastlevania3.html", cat: "platformer", desc: "dracula's curse, multiple playable characters on nes" },
  { name: "silent hill", url: "games/ugs/clsilenthill.html", cat: "horror", desc: "konami's ps1 psychological survival horror in a fog-filled town" },
  { name: "crash bandicoot", url: "games/ugs/clcrashbandicoot.html", cat: "platformer", desc: "naughty dog's ps1 mascot platformer" },
  { name: "crash bandicoot 2", url: "games/ugs/clcrashbandicoot2.html", cat: "platformer", desc: "cortex strikes back, improved sequel with warp rooms" },
  { name: "kirby super star", url: "games/ugs/clkirbysuperstar.html", cat: "platformer", desc: "snes kirby with multiple games and copy abilities" },
  { name: "kirby 64", url: "games/ugs/clkirby64.html", cat: "platformer", desc: "n64 kirby with combinable copy abilities" },
  { name: "advance wars", url: "games/ugs/cladvancewars.html", cat: "strategy", desc: "intelligent systems' gba turn-based tactics masterpiece" },
  { name: "advance wars 2", url: "games/ugs/cladvancewars2.html", cat: "strategy", desc: "black hole rising, expanded sequel with new COs" },
  { name: "metroid fusion", url: "games/ugs/clmetroidfusion.html", cat: "action", desc: "gba metroid with the terrifying sa-x stalking you" },
  { name: "super metroid", url: "games/ugs/clsupermetroid.html", cat: "action", desc: "snes masterpiece, the gold standard of metroidvania" },
  { name: "wario land 4", url: "games/ugs/clwarioland4.html", cat: "platformer", desc: "gba platformer with wario's greedy treasure hunting" },
  { name: "warioware inc.", url: "games/ugs/clwariowareinc.html", cat: "arcade", desc: "gba microgame madness, 5-second challenges at blazing speed" },
  { name: "perfect dark", url: "games/ugs/clperfectdark.html", cat: "shooter", desc: "rare's n64 spiritual successor to goldeneye with joanna dark" },
  { name: "wave race 64", url: "games/ugs/clwaverace64.html", cat: "racing", desc: "n64 jet ski racing with impressive wave physics" },
  { name: "secret of mana", url: "games/ugs/clsecretofmana.html", cat: "rpg", desc: "square's snes action rpg classic with ring menu system" },
  { name: "final fantasy", url: "games/ugs/clfinalfantasy.html", cat: "rpg", desc: "the original nes jrpg that started it all" },
  { name: "final fantasy vi", url: "games/ugs/clfinalfantasyVI.html", cat: "rpg", desc: "widely considered the best snes final fantasy" },
  { name: "final fantasy tactics", url: "games/ugs/clfinalfantasytactics.html", cat: "strategy", desc: "gba tactical rpg in the final fantasy universe" },
  { name: "harvest moon 64", url: "games/ugs/clharvestmoon64.html", cat: "simulation", desc: "n64 farming sim with romance and seasonal gameplay" },
  { name: "persona", url: "games/ugs/clpersona.html", cat: "rpg", desc: "atlus' ps1 jrpg blending high school life with demon summoning" },
  { name: "persona 2", url: "games/ugs/clpersona2.html", cat: "rpg", desc: "ps1 persona sequel with rumor-becomes-reality mechanics" },
  { name: "pepsiman", url: "games/ugs/clpepsiman.html", cat: "arcade", desc: "the ps1 meme classic, run as the pepsi mascot dodging obstacles" },
  { name: "doom 64", url: "games/ugs/cldoom64.html", cat: "shooter", desc: "unique n64 doom with original levels and darker atmosphere" },
  { name: "daggerfall", url: "games/ugs/cldaggerfall.html", cat: "rpg", desc: "elder scrolls ii, massive open-world dos rpg" },
  { name: "nfs underground", url: "games/ugs/clnfsunderground.html", cat: "racing", desc: "need for speed underground gba street racing" },
  { name: "nfs underground 2", url: "games/ugs/clnfsunderground2.html", cat: "racing", desc: "need for speed underground 2 gba with open world" },
  { name: "nfs most wanted", url: "games/ugs/clnfsmostwanted.html", cat: "racing", desc: "need for speed most wanted gba police chases" },

  // --- POKEMON ---
  { name: "pokemon emerald", url: "games/ugs/clpokemonemerald.html", cat: "rpg", desc: "gba pokemon with battle frontier and dual-team story" },
  { name: "pokemon fire red", url: "games/ugs/clpokemonfirered.html", cat: "rpg", desc: "gba remake of the original pokemon red with updated graphics" },
  { name: "pokemon crystal", url: "games/ugs/clpokemoncrystal.html", cat: "rpg", desc: "gbc pokemon with animated sprites and suicune storyline" },
  { name: "pokemon unbound", url: "games/ugs/clpokemonunbound.html", cat: "rpg", desc: "fan-made pokemon rom hack with massive content and gen 8 pokemon" },
  { name: "pokemon emerald rogue", url: "games/ugs/clPokemonemeraldrouge.html", cat: "rpg", desc: "roguelike pokemon rom hack with randomized runs" },
  { name: "pokemon snap", url: "games/ugs/clpokemonsnap.html", cat: "simulation", desc: "n64 pokemon photography rail shooter" },
  { name: "pokemon stadium", url: "games/ugs/clpokemonstadium.html", cat: "strategy", desc: "n64 pokemon 3d battles and mini-games" },

  // --- SONIC (GBA / DS) ---
  { name: "sonic advance", url: "games/ugs/clsonicadvance.html", cat: "platformer", desc: "gba sonic with 4 playable characters" },
  { name: "sonic advance 2", url: "games/ugs/clsonicadvance2.html", cat: "platformer", desc: "faster gba sonic sequel with trick actions" },
  { name: "sonic advance 3", url: "games/ugs/clsonicadvance3.html", cat: "platformer", desc: "tag-team gba sonic with partner mechanics" },
  { name: "sonic battle", url: "games/ugs/clsonicbattle.html", cat: "fighting", desc: "gba sonic fighting game with emerl the robot" },

  // --- COOKING / PAPA'S GAMES ---
  { name: "papa's freezeria", url: "games/ugs/clpapasfreezeria.html", cat: "cooking", desc: "serve frozen sundaes on a tropical island" },
  { name: "papa's cupcakeria", url: "games/ugs/clpapascupcakeria.html", cat: "cooking", desc: "bake and decorate cupcakes for picky customers" },
  { name: "papa's cheeseria", url: "games/ugs/clpapascheeseria.html", cat: "cooking", desc: "grill gourmet grilled cheese sandwiches" },
  { name: "papa's scooperia", url: "games/ugs/clpapasscooperia.html", cat: "cooking", desc: "scoop and serve ice cream cookie sundaes" },
  { name: "papa's sushiria", url: "games/ugs/clpapassushiria.html", cat: "cooking", desc: "roll sushi and serve bubble tea" },
  { name: "papa's taco mia", url: "games/ugs/clpapastacomia.html", cat: "cooking", desc: "build tacos with precise toppings" },
  { name: "papa's wingeria", url: "games/ugs/clpapaswingeria.html", cat: "cooking", desc: "fry and sauce chicken wings to order" },
  { name: "papa's hot doggeria", url: "games/ugs/clpapashotdoggeria.html", cat: "cooking", desc: "serve hot dogs at a baseball stadium" },
  { name: "papa's pastaria", url: "games/ugs/clpapaspastaria.html", cat: "cooking", desc: "cook pasta and serve it with bread and sauce" },
  { name: "papa's pancakeria", url: "games/ugs/clpapaspancakeria.html", cat: "cooking", desc: "flip pancakes and stack breakfast orders" },
  { name: "cooking mama", url: "games/ugs/clcookingmama.html", cat: "cooking", desc: "ds cooking sim with mini-game recipe steps" },
  { name: "cooking mama 2", url: "games/ugs/clcookingmama2.html", cat: "cooking", desc: "sequel with more recipes and gardening" },

  // --- POPULAR FLASH CLASSICS ---
  { name: "friday night funkin'", url: "games/ugs/clfridaynightfunkin.html", cat: "rhythm", desc: "indie rhythm game, rap battle to win your girlfriend's heart" },
  { name: "super smash flash 2", url: "games/ugs/clsupersmashflash2.html", cat: "fighting", desc: "fan-made smash bros with huge roster and online play" },
  { name: "jacksmith", url: "games/ugs/cljacksmith.html", cat: "strategy", desc: "forge weapons for warriors heading into battle, flipline classic" },
  { name: "strike force heroes", url: "games/ugs/clstrikeforceheroes.html", cat: "shooter", desc: "flash platform shooter with classes and upgrades" },
  { name: "strike force heroes 2", url: "games/ugs/clstrikeforceheroes2.html", cat: "shooter", desc: "sequel with more classes, weapons, and campaign missions" },
  { name: "strike force heroes 3", url: "games/ugs/clstrikeforceheroes3.html", cat: "shooter", desc: "third entry with squad customization and hero abilities" },
  { name: "fancy pants adventure", url: "games/ugs/clfancypantsadventure.html", cat: "platformer", desc: "smooth stick-figure platformer with stylish animations" },
  { name: "fancy pants adventure 2", url: "games/ugs/clfancypantsadventure2.html", cat: "platformer", desc: "sequel with more moves, levels, and buttery-smooth gameplay" },
  { name: "cactus mccoy", url: "games/ugs/clcactusmccoy.html", cat: "platformer", desc: "run-and-gun platformer as a cursed cactus cowboy" },
  { name: "cactus mccoy 2", url: "games/ugs/clcactusmccoy2.html", cat: "platformer", desc: "sequel with more weapons and treasure hunting" },
  { name: "age of war", url: "games/ugs/clageofwar.html", cat: "strategy", desc: "evolve through ages to destroy the enemy base" },
  { name: "age of war 2", url: "games/ugs/clageofwar2.html", cat: "strategy", desc: "sequel with more units, ages, and special attacks" },
  { name: "electric man 2", url: "games/ugs/clelectricman2.html", cat: "fighting", desc: "stick figure fighting tournament with slow-mo combos" },
  { name: "gun mayhem", url: "games/ugs/clgunmayhem.html", cat: "shooter", desc: "platform shooter, knock opponents off the stage" },
  { name: "gun mayhem 2", url: "games/ugs/clgunmayhem2.html", cat: "shooter", desc: "sequel with more weapons and custom characters" },
  { name: "hobo", url: "games/ugs/clhobo.html", cat: "action", desc: "beat-em-up as a hobo fighting through the streets" },
  { name: "hobo 2", url: "games/ugs/clhobo2.html", cat: "action", desc: "hobo prison brawl, escape from jail" },
  { name: "hobo 3", url: "games/ugs/clhobo3.html", cat: "action", desc: "wanted, hobo on the run from the law" },
  { name: "hobo 4", url: "games/ugs/clhobo4.html", cat: "action", desc: "hobo goes to war in total war" },
  { name: "hobo 5", url: "games/ugs/clhobo5.html", cat: "action", desc: "hobo in space, punching aliens" },
  { name: "hobo 6", url: "games/ugs/clhobo6.html", cat: "action", desc: "hobo vs hell, fighting demons" },
  { name: "hobo 7", url: "games/ugs/clhobo7.html", cat: "action", desc: "hobo in heaven, the final brawl" },
  { name: "bob the robber", url: "games/ugs/clbobtherobber.html", cat: "adventure", desc: "stealth puzzle game, sneak past guards and steal loot" },
  { name: "bob the robber 2", url: "games/ugs/clbobtherobber2.html", cat: "adventure", desc: "sequel with harder security and more gadgets" },
  { name: "fireboy and watergirl", url: "games/ugs/clfireboyandwatergirl.html", cat: "puzzle", desc: "two-player co-op platformer in the forest temple" },
  { name: "fireboy and watergirl 2", url: "games/ugs/clfireboyandwatergirl2.html", cat: "puzzle", desc: "light temple, new puzzles with light mechanics" },
  { name: "fireboy and watergirl 3", url: "games/ugs/clfireboyandwatergirl3.html", cat: "puzzle", desc: "ice temple, slippery surfaces and ice puzzles" },
  { name: "red ball", url: "games/ugs/clredball.html", cat: "platformer", desc: "physics-based platformer with a bouncy red ball" },
  { name: "red ball 3", url: "games/ugs/clredball3.html", cat: "platformer", desc: "third entry with new worlds and obstacles" },
  { name: "red ball 4", url: "games/ugs/clredball4.html", cat: "platformer", desc: "save the world from evil squares turning everything square" },
  { name: "riddle school", url: "games/ugs/clriddleschool.html", cat: "puzzle", desc: "point-and-click escape from a boring school" },
  { name: "riddle school 2", url: "games/ugs/clriddleschool2.html", cat: "puzzle", desc: "escape school again with harder puzzles" },
  { name: "riddle school 3", url: "games/ugs/clriddleschool3.html", cat: "puzzle", desc: "third school escape with plot twists" },
  { name: "riddle transfer", url: "games/ugs/clriddletransfer.html", cat: "puzzle", desc: "continuation of riddle school, escape a research facility" },
  { name: "riddle transfer 2", url: "games/ugs/clriddletransfer2.html", cat: "puzzle", desc: "finale of the riddle school series" },
  { name: "the impossible quiz 2", url: "games/ugs/climpossiblequiz2.html", cat: "puzzle", desc: "more absurd trick questions and unexpected deaths" },
  { name: "angry birds", url: "games/ugs/clangrybirds.html", cat: "arcade", desc: "launch birds at pig structures in this mobile classic" },
  { name: "jetpack joyride", url: "games/ugs/cljetpackjoyride.html", cat: "arcade", desc: "endless runner with jetpacks, vehicles, and coin collecting" },
  { name: "bad ice cream", url: "games/ugs/clbadicecream.html", cat: "arcade", desc: "two-player ice cream collecting with ice-wall mechanics" },
  { name: "bad ice cream 2", url: "games/ugs/clbadicecream2.html", cat: "arcade", desc: "sequel with new fruits and obstacles" },
  { name: "bad ice cream 3", url: "games/ugs/clbadicecream3.html", cat: "arcade", desc: "third entry with more flavors and enemies" },
  { name: "motherload", url: "games/ugs/clmotherload.html", cat: "adventure", desc: "dig deep into mars for minerals and upgrade your mining pod" },
  { name: "swords and sandals 2", url: "games/ugs/clswordsandsandals2.html", cat: "fighting", desc: "gladiator rpg with turn-based arena combat" },
  { name: "swords and souls", url: "games/ugs/clswordsandsouls.html", cat: "rpg", desc: "train a gladiator in mini-games, fight in the arena" },
  { name: "stick rpg complete", url: "games/ugs/clstickrpgcomplete.html", cat: "rpg", desc: "2d stick figure life sim, get a job, buy a house, rule the city" },
  { name: "line rider", url: "games/ugs/cllinerider.html", cat: "casual", desc: "draw lines for a sled rider to ride, a timeless classic" },
  { name: "qwop", url: "games/ugs/clqwop.html", cat: "arcade", desc: "notoriously difficult olympic running game using q, w, o, p keys" },
  { name: "my friend pedro", url: "games/ugs/clmyfriendpedro.html", cat: "action", desc: "the original flash game, slow-mo banana-guided shooting" },
  { name: "alien hominid", url: "games/ugs/clalienhominid.html", cat: "action", desc: "the newgrounds flash classic, alien vs fbi run-and-gun" },
  { name: "learn to fly 2", url: "games/ugs/cllearntofly2.html", cat: "arcade", desc: "sequel with more upgrades and flight modes" },
  { name: "learn to fly 3", url: "games/ugs/cllearntofly3.html", cat: "arcade", desc: "third penguin launch game with payload mode" },
  { name: "earn to die", url: "games/ugs/clearntodie.html", cat: "racing", desc: "upgrade your car and drive through zombie hordes" },
  { name: "bloons td 3", url: "games/ugs/clbloonsTD3.html", cat: "tower defense", desc: "third bloons tower defense with specialty buildings" },
  { name: "bloons td 4", url: "games/ugs/clbloonsTD4.html", cat: "tower defense", desc: "fourth entry with tower upgrades and new maps" },
  { name: "territory war", url: "games/ugs/clterritorywar.html", cat: "strategy", desc: "worms-style stick figure turn-based combat" },
  { name: "bubble tanks", url: "games/ugs/clbubbletanks.html", cat: "shooter", desc: "navigate bubble fields and grow your bubble tank" },
  { name: "bubble tanks 2", url: "games/ugs/clbubbletanks2.html", cat: "shooter", desc: "sequel with more evolutions and enemy types" },
  { name: "bubble tanks 3", url: "games/ugs/clbubbletanks3.html", cat: "shooter", desc: "create custom tanks with modular parts" },
  { name: "achilles", url: "games/ugs/clachillies.html", cat: "action", desc: "side-scrolling greek warrior beat-em-up" },
  { name: "madness accelerant", url: "games/ugs/clmadnessaccelerant.html", cat: "action", desc: "madness combat flash beat-em-up" },
  { name: "madness: project nexus", url: "games/ugs/clmadnesscombatnexus.html", cat: "action", desc: "madness combat arena shooter with story mode" },
  { name: "warfare 1944", url: "games/ugs/clwarfare1944.html", cat: "strategy", desc: "ww2 strategy, deploy troops across the battlefield" },
  { name: "bomberman", url: "games/ugs/clbomberman.html", cat: "arcade", desc: "classic bomberman maze with power-ups and explosions" },
  { name: "sugar sugar", url: "games/ugs/clsugarsugar.html", cat: "puzzle", desc: "draw lines to guide sugar into cups, relaxing puzzle" },
  { name: "wheely", url: "games/ugs/clwheely.html", cat: "puzzle", desc: "point-and-click puzzle with a cute red car" },
  { name: "wheely 2", url: "games/ugs/clwheely2.html", cat: "puzzle", desc: "wheely searches for his girlfriend car" },
  { name: "wheely 3", url: "games/ugs/clwheely3.html", cat: "puzzle", desc: "wheely goes on a carnival adventure" },
  { name: "wheely 4", url: "games/ugs/clwheely4.html", cat: "puzzle", desc: "wheely travels through time" },
  { name: "wheely 5", url: "games/ugs/clwheely5.html", cat: "puzzle", desc: "wheely becomes an armageddon detective" },
  { name: "wheely 6", url: "games/ugs/clwheely6.html", cat: "puzzle", desc: "wheely's fairytale adventure" },
  { name: "wheely 7", url: "games/ugs/clwheely7.html", cat: "puzzle", desc: "wheely detective solves a mystery" },
  { name: "wheely 8", url: "games/ugs/clwheely8.html", cat: "puzzle", desc: "wheely's alien encounter adventure" },
  { name: "troll face quest 1", url: "games/ugs/cltrollfacequest1.html", cat: "puzzle", desc: "trollface meme point-and-click puzzle game" },
  { name: "troll face quest 2", url: "games/ugs/cltrollfacequest2.html", cat: "puzzle", desc: "more trollface puzzles with trick solutions" },
  { name: "dead zed", url: "games/ugs/cldeadzed.html", cat: "shooter", desc: "zombie siege defense with sniper mechanics" },
  { name: "dead zed 2", url: "games/ugs/cldeadzed2.html", cat: "shooter", desc: "sequel with more weapons and base management" },
  { name: "clear vision", url: "games/ugs/clclearvision.html", cat: "shooter", desc: "stick figure sniper assassination missions" },
  { name: "clear vision 2", url: "games/ugs/clclearvision2.html", cat: "shooter", desc: "more sniper missions with story progression" },
  { name: "clear vision 3", url: "games/ugs/clclearvision3.html", cat: "shooter", desc: "third entry with expanded storyline" },
  { name: "clear vision 4", url: "games/ugs/clclearvision4.html", cat: "shooter", desc: "elite sniper missions continue" },
  { name: "clear vision 5", url: "games/ugs/clclearvision5.html", cat: "shooter", desc: "conclusion of the sniper saga" },

  // --- POPULAR HTML5 / MODERN GAMES ---
  { name: "ovo", url: "games/ugs/clovo.html", cat: "platformer", desc: "fast-paced stickman parkour platformer with wall jumps" },
  { name: "level devil", url: "games/ugs/clleveldevil.html", cat: "platformer", desc: "platformer where the level itself tries to kill you" },
  { name: "suika game", url: "games/ugs/clsuika.html", cat: "puzzle", desc: "viral watermelon merge game, drop and combine fruits" },
  { name: "infinite craft", url: "games/ugs/clinfinitecraft.html", cat: "casual", desc: "neal.fun's viral element combining game, create everything" },
  { name: "antimatter dimensions", url: "games/ugs/clantimatterdimensions.html", cat: "idle", desc: "deep incremental game with antimatter production and dimensions" },
  { name: "drive mad", url: "games/ugs/cldrivemad.html", cat: "racing", desc: "physics-based driving through obstacle courses" },
  { name: "stickman hook", url: "games/ugs/clstickmanhook.html", cat: "arcade", desc: "swing through levels with grappling hook physics" },
  { name: "hole.io", url: "games/ugs/clholeio.html", cat: "arcade", desc: "be a black hole swallowing everything in the city" },
  { name: "slither.io", url: "games/ugs/clslitherio.html", cat: "arcade", desc: "multiplayer snake game, grow by eating orbs" },
  { name: "basket bros", url: "games/ugs/clbasketbros.html", cat: "sports", desc: "2v2 basketball with power-ups and dunks" },
  { name: "drift boss", url: "games/ugs/cldriftboss.html", cat: "racing", desc: "one-button drifting game on a winding road" },
  { name: "basketball legends", url: "games/ugs/clbasketballlegends.html", cat: "sports", desc: "1v1 or 2v2 basketball with real player likenesses" },
  { name: "football legends", url: "games/ugs/clfootballlegends.html", cat: "sports", desc: "2-player american football with power-ups" },
  { name: "big tower tiny square 2", url: "games/ugs/clbigtowertinysquare2.html", cat: "platformer", desc: "sequel with harder tower climbing challenges" },
  { name: "dreadhead parkour", url: "games/ugs/cldreadheadparkour.html", cat: "platformer", desc: "parkour platformer with smooth animations" },
  { name: "escape road", url: "games/ugs/clescaperoad.html", cat: "racing", desc: "police chase escape driving game" },
  { name: "a small world cup", url: "games/ugs/clasmallworldcup.html", cat: "sports", desc: "physics-based ragdoll soccer" },
  { name: "tiny fishing", url: "games/ugs/cltinyfishing.html", cat: "casual", desc: "idle fishing game, catch fish and upgrade your rod" },
  { name: "house of hazards", url: "games/ugs/clhouseofhazards.html", cat: "casual", desc: "multiplayer party game setting traps in a house" },
  { name: "deepest sword", url: "games/ugs/cldeepestsword.html", cat: "platformer", desc: "platformer with an absurdly long sword" },
  { name: "bacon may die", url: "games/ugs/clbaconmaydie.html", cat: "action", desc: "beat-em-up as a bacon strip fighting food enemies" },
  { name: "free rider", url: "games/ugs/clfreerider.html", cat: "racing", desc: "draw tracks and ride a bike on them" },
  { name: "free rider 2", url: "games/ugs/clfreerider2.html", cat: "racing", desc: "sequel with trucks and helicopter options" },
  { name: "free rider 3", url: "games/ugs/clfreerider3.html", cat: "racing", desc: "third entry with community track sharing" },
  { name: "cat mario", url: "games/ugs/clcatmario.html", cat: "platformer", desc: "troll platformer with invisible traps (syobon action)" },
  { name: "slow roads", url: "games/ugs/clslowroads.html", cat: "racing", desc: "peaceful procedural driving through beautiful landscapes" },
  { name: "little alchemy 2", url: "games/ugs/cllittlealchemy2.html", cat: "puzzle", desc: "combine elements to discover 720+ items" },
  { name: "adventure capitalist", url: "games/ugs/cladventurecapitalist.html", cat: "idle", desc: "idle business tycoon, manage lemonade to oil companies" },
  { name: "crossy road", url: "games/ugs/clcrossyroad.html", cat: "arcade", desc: "endless frogger with voxel art and collectible characters" },
  { name: "eggy car", url: "games/ugs/cleggycar.html", cat: "racing", desc: "physics-based car driving with a fragile egg on top" },
  { name: "granny", url: "games/ugs/clgranny.html", cat: "horror", desc: "escape granny's house in 5 days, stealth horror" },
  { name: "jelly truck", url: "games/ugs/cljellytruck.html", cat: "racing", desc: "drive a wobbly jelly truck through obstacles" },
  { name: "pou", url: "games/ugs/clpou.html", cat: "casual", desc: "virtual pet care game, feed and play with your pou" },
  { name: "unfair mario", url: "games/ugs/clunfairmario.html", cat: "platformer", desc: "super mario but every block is a trap" },
  { name: "blightborne", url: "games/ugs/clblightborne.html", cat: "action", desc: "dark action roguelike with gothic atmosphere" },
  { name: "geometry dash lite", url: "games/ugs/clgeometrydashlite.html", cat: "platformer", desc: "rhythm platformer through geometric obstacles" },
  { name: "doge miner 2", url: "games/ugs/cldogeminer2.html", cat: "idle", desc: "mine dogecoins and explore space in this idle sequel" },
  { name: "burrito bison", url: "games/ugs/clburritobison.html", cat: "arcade", desc: "launch a wrestling bison through gummy bears for distance" },
  { name: "bubble shooter", url: "games/ugs/clbubbleshooter.html", cat: "puzzle", desc: "classic match-3 bubble popping game" },

  // --- CLASSIC ARCADE ---
  { name: "pac-man", url: "games/ugs/clpacman.html", cat: "arcade", desc: "namco's 1980 maze game, eat dots and avoid ghosts" },
  { name: "galaga", url: "games/ugs/clgalaga.html", cat: "arcade", desc: "classic 1981 space shooter, destroy alien formations" },
  { name: "space invaders", url: "games/ugs/clspaceinvaders.html", cat: "arcade", desc: "taito's 1978 alien invasion shooter that started it all" },
  { name: "chess", url: "games/ugs/clchess.html", cat: "strategy", desc: "the classic board game of strategy" },
  { name: "tetris", url: "games/ugs/cltetris.html", cat: "puzzle", desc: "the original block-stacking puzzle game" },

  // --- FIGHTING GAMES ---
  { name: "mortal kombat", url: "games/ugs/clmortalkombat.html", cat: "fighting", desc: "midway's brutal arcade fighter with fatalities" },
  { name: "street fighter 2", url: "games/ugs/clstreetfighter2.html", cat: "fighting", desc: "capcom's iconic arcade fighter that defined the genre" },
  { name: "street fighter alpha 3", url: "games/ugs/clstreetfighteralpha3.html", cat: "fighting", desc: "capcom alpha series with isms fighting styles" },
  { name: "bleach vs naruto", url: "games/ugs/clbleachvsnaruto.html", cat: "fighting", desc: "fan-made anime crossover fighting game" },
  { name: "dbz devolution", url: "games/ugs/cldbzdevolution.html", cat: "fighting", desc: "dragon ball z browser fighting game" },

  // --- MISC ---
  { name: "counter-strike 1.6", url: "games/ugs/clcs1.6.html", cat: "shooter", desc: "the legendary tactical fps in your browser" },
  { name: "animal crossing: wild world", url: "games/ugs/clanimalcrossingwildworld.html", cat: "simulation", desc: "ds life sim with villagers, fishing, and fossil collecting" },
  { name: "world's hardest game 3", url: "games/ugs/clworldshardestgame3.html", cat: "arcade", desc: "third impossibly hard square navigation game" },
  { name: "world's hardest game 4", url: "games/ugs/clworldshardestgame4.html", cat: "arcade", desc: "fourth iteration of impossible difficulty" },
];
